export const modalTable: string;
export const calendarFilterRow: string;
export const colXs1: string;
export const colXs7: string;
export const colXs4: string;
export const calendarFilterText: string;
export const formFieldError: string;
export const requiredFormFieldUnsatisfied: string;
export const requiredFormFieldSatisfied: string;
