export const skinBlue: string;
export const mainHeader: string;
export const navbar: string;
export const dropdownMenu: string;
export const select2ContainerDefault: string;
export const select2SelectionMultiple: string;
export const select2SelectionChoice: string;
export const userHeader: string;
export const itemLink: string;
