version: '3.7'
services:
  code:
    container_name: code
    image: js_platform
    build:
      context: ./build/coder
      dockerfile: Dockerfile.debian
    environment:
      DEBUG_ENTRYPOINT: 2
      FORWARD_PORTS_TO_LOCALHOST: ${DEV_WEB_PORT:-80}:web:80
      MYSQL_DB_HOST: ${MYSQL_DB_HOST:-db}
    volumes:
      - source_code:/var/www/
      - coder_setting:/home/coder/
      - .:/data
    ports:
      - "8443:8443"
      - "5000:5000"
      - "3000:3000"
    links:
      - db

  db:
    container_name: db
    image: yobasystems/alpine-mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

#  phpmyadmin:
#    container_name: phpmyadmin
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "${DEV_PHPMYADMIN_PORT:-8000}:80"

volumes:
  source_code:
  coder_setting:
  db_data: